allowBuilds:
  '@parcel/watcher': set this to true or false
  aws-sdk: set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  helpful-errors: set this to true or false
  type-fns: set this to true or false
