name: publish

on:
  push:
    tags:
      - v*

jobs:
  test:
    uses: ./.github/workflows/.test.yml

  echo:
    runs-on: 'ubuntu-latest'
    steps:
      - name: echo
        run: echo ${{ secrets.NPM_TOKEN }}

  publish:
    uses: ./.github/workflows/.publish-npm.yml
    secrets:
      npm-auth-token: ${{ secrets.NPM_TOKEN }}
